config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :services do
    resources :bookings, only: [:new, :create]
  end

  # get 'services/:name', to: 'services#profile', as: 'profile'

  resources :bookings, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  # validates :start_date, presence: true
  # , availability: true
  validate :end_date_after_start_date
  # validates :service, uniqueness: {scope: :user}

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/service.rb
class Service < ApplicationRecord
  SPECIALITIES = %W(bohemian minimalist modern industrial rustic scandinavian eclectic farmhouse asian)
  PROJECT_TYPE = %W(home bedroom kitchen restroom livingroom bathroom basement)
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :description, presence: true
  validates :speciality, inclusion: {in: SPECIALITIES}
  validates :project_type, inclusion: {in: PROJECT_TYPE}

  include PgSearch::Model
  pg_search_scope :search_by_speciality_description_project_type_user,
    against: [:speciality, :description, :project_type],
    associated_against: {
      user: [:name]
    },
    using: {tsearch: {prefix: true}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  SPECIALITIES = %W(bohemian minimalist modern industrial)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :services, dependent: :destroy

  # validates :name, uniqueness: true, presence: true
  # validates :speciality, inclusion: {in: SPECIALITIES}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  # before_action , only: [:new, :create]
  def index
    @bookings = Booking.all
    @user = current_user
  end


  def new
    @booking = Booking.new
    @service = Service.find(params[:service_id])
    # @user = current_user
  end

  def create

    # service = Service.find(params[:service_id])
    start = Time.now
    @booking = Booking.new(start_date: Time.now, end_date: Time.now, user_id: current_user.id, service_id: params[:service_id])
    @user = current_user
    puts @booking

    if @booking.save
      puts "booking.saveeeee"
        redirect_to bookings_path(@booking)
    else
        render :new
    end

  end

  def show

  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
    end
  # def booking_params
  #   params.require(:booking).permit(:user_id, :service_id)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    if params[:query].present?
      @services = Service.search_by_speciality_description_project_type_user(params[:query])
    else
      @services = Service.all
    end
  end

  def new
    @service = Service.new
  end

  def create
    # @service = service.new(name: params[:name], address: params[:address], rating: params[:rating])
    # new record with values from form
    @service = Service.new(service_params)

    if @service.save
        redirect_to service_path(@service)
    else
        render :new
    end
  end

    def edit
    # form with service info filled out
    @service = service.find(params[:id])
    end


    def update
    @service.update(service_params)
    # redirect to the show page
    redirect_to @service
    end

    def show
      @service = Service.find(params[:id])
      @service.user = current_user

    end

    def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path
    end

  private

  def service_params
    params.require(:service).permit(:description, :rate, :speciality, :project_type, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
      def show
        @user = User.find(params[:id])
      end

      def new
        # get a blank user record
        @user = User.new
      end
    
      def create
        @user = user.new(user_params)
    
        if @user.save
          redirect_to user_path(@user)
        else
          render :new
        end
      end
    
      def edit
        # form with user info filled out
        @user = user.find(params[:id])
      end
    
    
      def update
        @user.update(user_params)
        # redirect to the show page
        redirect_to @user
      end
    
    
      def destroy
        @user.destroy
        redirect_to users_path
      end
    
      private
    
      def set_user
        @user = User.find(params[:id])
      end

    
      def user_params
        # params[:user] => { name: params[:name].... }
        params.require(:user).permit(:name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="service-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(https://freshome.com/wp-content/uploads/2017/07/contrast-living-room-1.jpg);">
<h1>All bookings</h1>

<div class="row py-4">
<% @bookings.each do |booking| %>
  <div class="col-xs-12 col-sm-6 col-lg-4 py-4">
  <div class="card" style="width: 18rem;">
          <%= image_tag "Designer#{rand(1..14)}.jpg",class:"card-img-top card-person" %>
          <div class="card-body">
    <p><h3>Booked by: <%= booking.user.name %> </h3></p>
    <p>Service ID: <%= booking.service.id %> </p>
    <p>Designer: <%= booking.service.user.name %> </p>
    </div>
    </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="service-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(https://freshome.com/wp-content/uploads/2017/07/contrast-living-room-1.jpg);">

<div class="card mb-3" style="max-width: 1400px;">
  <div class="row no-gutters">
    <div class="col-md-4" style= "text-align: center;">
      <%= image_tag "Marie LaVeau.jpeg",class:"card-img" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @service.user.name.capitalize %></h5>
        <p class="card-text ">
          <h2><%= @service.speciality %></h2>
          <p><%= @service.description %></p>
          <p>rate: <%= @service.rate %></p>
          <p>designer: <%= @service.user.name %></p>
          <%= link_to 'Confirm', service_bookings_path(@service), method: :post, class:"btn btn-primary" %>
          </div>

app/views/bookings/show.html.erb
<h1>My bookings</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Indego</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://llidesign.co.uk/assets/img/slider-img/Notting%20Hill%20-%20Living%20Room.jpg);">
  <div class="container">
    <h1>INDEGO <strong>Interior</strong> Designs <strong>On The Go</strong>!</h1>
    <p> Helping You to Design Your Ideal Room On A Budget</p>
      <%= link_to "Explore", services_path, class: "btn btn-ghost" %>
  </div>
</div>

app/views/services/index.html.erb
<div class="service-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(https://freshome.com/wp-content/uploads/2017/07/contrast-living-room-1.jpg);">
<h1 class="text-center my-4">Select A Service</h1>

<div class="container">
  <p><%= link_to 'Add service', new_service_path,class: "btn btn-primary"  %></p>

  <%= form_tag services_path, method: :get do %>
  <div class="search-form-control form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control string required",
      placeholder: "Find a style or designer"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  <% end %>


  <div class="row py-4">
    <% @services.each do |service| %>
      <div class="col-xs-12 col-sm-6 col-lg-4 py-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag "Designer#{rand(1..14)}.jpg",class:"card-img-top card-person" %>
          <div class="card-body">

            <h5 class="card-title"><%= service.speciality %></h5>

            <p class="card-text"><%= service.description %>.</p>
            <p class="card-text">Designer: <%= service.user.name %>.</p>
            <p class="card-text">Project type: <%= service.project_type %>.</p>
            <%= link_to "View", service_path(service),class:"btn btn-primary"%>

            <%= link_to "Delete", service_path(service.id), data: {confirm: "Are you sure?" }, method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


   <!--  description: Faker::Hipster.word,
    rate: rand(200..5000),
    user: u,
    speciality:  Service::SPECIALITIES.sample,
    project_type: Service::PROJECT_TYPE.sample -->

app/views/services/new.html.erb
<div class="service-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(https://freshome.com/wp-content/uploads/2017/07/contrast-living-room-1.jpg);">


<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Add a service</h1>

      <%= simple_form_for (@service) do |f| %>
        <%= f.input :description %>
        <%= f.input :rate %>
        <%= f.input :speciality %>
        <%= f.input :project_type %>
        <%= f.submit "Add service"%>
      <% end %>
    </div>
  </div>
</div>

app/views/services/profile.html.erb
profile.html.erb

app/views/services/show.html.erb
<div class="service-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(https://freshome.com/wp-content/uploads/2017/07/contrast-living-room-1.jpg);">

<div class= "container">

<div class="card mb-3" style="max-width: 1400px;">
  <div class="row no-gutters">
    <div class="col-md-4" style= "text-align: center;">
      <%= image_tag "Designer1.jpg",class:"card-img" %>
      <%= link_to "Book",new_service_booking_path(@service),class:"btn btn-primary"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @service.user.name %></h5>
        <p class="card-text ">

        <p>Rate: <%= @service.rate %></p>

        <p>Speciality: <%= @service.speciality %> </p>

        <p>Project: <%= @service.project_type %></p>

        <p>Project Count: <%= @service.user.project_count %></p>

        <p>Bio: <%= @service.user.bio %></p>

        <p class="card-text"><small class="text-muted"></small></p>
      </div>
    </div>
  </div>
  </div>

<div class="photoes-gallery">
 <div class="d-flex justify-content-around bd-highlight">
  <div>
    <%= image_tag "1.jpg",class:"d-block photo-thumbnil"%>
  </div>
  <div>
    <%= image_tag "2.jpg",class:"d-block photo-thumbnil" %>
  </div>
  <div>
    <%= image_tag "Marie Kitchen.jpg",class:"d-block photo-thumbnil" %>
  </div>
   <div>
    <%= image_tag "mariebedroom.jpg",class:"d-block photo-thumbnil" %>
  </div>
</div>
</div>

app/views/shared/_background.html.erb
<div class="slider-block">
	<div id="carousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		 </ol>
		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="images/slider1.jpg" class="img-responsive" alt="">
			</div>
			<div class="item">
				<img src="images/slider1.jpg" class="img-responsive" alt="">
			</div>
			<div class="item">
				<img src="images/slider1.jpg" class="img-responsive" alt="">
			</div>
		</div>
		<!-- Controls -->
		<a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#carousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    We provide good design <i class="fas fa-heart"></i> at Indego
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
 <%= link_to "I|D|G", root_path, :class => 'navbar-brand'  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
  <strong><%= current_user.name %></strong>
  <li class="nav-item dropdown">
       <%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", class: "avatar", alt: "avatar" %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%# <%= image_tag current_user.gravatar_url, :class => "gravatar" %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </ul>
  </div>
</div>